server:
  port: ${APP_PORT:8081}

spring:
  application:
    name: solicitudes-service
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2

security:
  jwt:
    public: classpath:public.pem
    ttl-seconds: 3600

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    url: /v1/api-docs
    persist-authorization: true
  packages-to-scan: co.com.solicitudes.api
  paths-to-match: /api/**

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10s
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10s

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
